# Header
menu:
  主页: /
  关于: /about
  归档: /archives
rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: false
mathjax: false

# Sidebar
sidebar: right
widgets:
- tagcloud
- category
- recent_posts
- links
- tag
- archive

# Links
links:
  知乎: http://zhihu.com
  我的邮箱: http://youxiang.info

# Miscellaneous
google_analytics:
baidu_analytics: 1560044f7350c95ffd183a737b08e65d
favicon: /favicon.png
twitter:
google_plus:
fb_admins: 
fb_app_id:

# Baidu share
baidushare: true