title:
  archive: Archive
  category: Category
  tag: Tag

author: Author

menu:
  home: 首页
  archives: 归档
  categories: 分类
  tags: 标签
  links: 链接
  about: 关于
  search: 搜索
  android: Android
  osx: OS X
  commonweal: 公益404s

sidebar:
  overview: Overview
  toc: Table of Contents

post:
  sticky: Sticky
  posted: Posted on
  in: In
  read_more: Read more
  untitled: Untitled
  toc_empty: This post does not have a Table of Contents

page:
  totally: Totally
  tags: tags

footer:
  powered: "Powered by %s"
  theme: Theme

counter:
  tag_cloud:
    zero: No tags
    one: 1 tag in total
    other: "%d tags in total"

  categories:
    zero: No categories
    one: 1 category in total
    other: "%d categories in total"

  archive_posts:
    zero: No posts.
    one: 1 post.
    other: "%d posts in total."

state:
  posts: posts
  pages: pages
  tags: tags
  categories: categories

cheers:
  um: Um..
  ok: OK
  nice: Nice
  good: Good
  great: Great
  excellent: Excellent

keep_on: Keep on posting.

symbol:
  comma: ', '
  period: '. '
